// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4u9ZNcoBIMsIbQoEkPw-9pD16GEfEasg',
    appId: '1:357972744272:web:cea2d9ab9deb16dfe19955',
    messagingSenderId: '357972744272',
    projectId: 'letmegoo-2aab1',
    authDomain: 'letmegoo-2aab1.firebaseapp.com',
    storageBucket: 'letmegoo-2aab1.firebasestorage.app',
    measurementId: 'G-CEPB2WWJQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcglrv82GSKICJ7efUsy4tVPTbq2wN0UY',
    appId: '1:357972744272:android:d4cea1bc85d08e9de19955',
    messagingSenderId: '357972744272',
    projectId: 'letmegoo-2aab1',
    storageBucket: 'letmegoo-2aab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9JgcdQFlsmOw02YM0rNA0L6KpATdFpA',
    appId: '1:357972744272:ios:fc210b69324a0b93e19955',
    messagingSenderId: '357972744272',
    projectId: 'letmegoo-2aab1',
    storageBucket: 'letmegoo-2aab1.firebasestorage.app',
    androidClientId: '357972744272-8m6c9fgd892kdb8iitv06d25n3pjatk5.apps.googleusercontent.com',
    iosClientId: '357972744272-u2nc11kllos6vnilgvhi1khreuar0n0r.apps.googleusercontent.com',
    iosBundleId: 'com.letmegoo.mobile',
  );

}